### ISSUE TITLE
TASK LIST - Q3 dashboard

### ISSUE THREAD

**Issue by nmcdavid** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#37]
[Link](https://docs.google.com/document/d/1AyCoNM3aVjnES0ZwkvfU5bT3zextFjdJt1fbFtc_5sU/edit?usp=sharing) to QA/QC Guide

[Link](https://www.google.com/url?q=https://tableau.usaid.gov/views/Q3QuarterlyOHADashboard/Intro?iframeSizedToWindow%3Dtrue%26:embed%3Dy%26:showAppBanner%3Dfalse%26:display_count%3Dno%26:showVizHome%3Dno&sa=D&source=hangouts&ust=1535465173460000&usg=AFQjCNEHlpw0F2e9XZk5OJwFxEJ7S_UjzA) to Dashboards on USAID Server

- [x] Global 01: Target Achievement - **Karin** (#43)
- [x] OU.01: Percent Achievement - **Aaron** (#38)
- [x] OU.02: Agency Contribution - **Aaron** (#41)
- [x] OU.03: Quarterly Results - **Aaron** (#42)
- [ ] OU.04: Partner Achievement - **Karin**
- [ ] OU.05: Partner Comparison - **Karin**
- [ ] OU.06: Partner Contribution - **Karin**
- [x] OU.07: Age/Sex Results - **Aaron** (#44) --> OVC needs review
- [ ] TX.01: Retention **Nashiva**
- [ ] TX.02: Retention Age/Sex  **Nashiva**
- [ ] TX.03: Viral Load **Nashiva**
- [ ] TX.04: Viral Load Age/Sex **Nashiva**
- [ ] TX.05: Routine VL **Nashiva**
- [ ] TX.06: TX_CURR with VL **Nashiva**
- [ ] HTS.01: Modality 
- [ ] HTS.02: Positivity by Age/Sex
- [ ] HTS.03: Index Testing
- [ ] PMTCT.01: Positivity - **Nashiva**
- [x] KP.01: KP_PREV  - ~~**Nashiva**~~ **Maria** 
- [ ] KP.02: HTS - ~~**Nashiva**~~  **Maria** (#40 )
- [ ] KP.03: PrEP - ~~**Nashiva**~~ **Maria** (#39 )
- [x] KP.04: TX_NEW - ~~**Nashiva**~~  **Maria**
- [ ] VMMC.01: Age Bands - **Josh** 
- [ ] VMMC.02: Age Trends - **Josh**
- [ ] VMMC.03: HIV Testing - **Josh**

**Comment by jaliasd** [comment]
Is there a QC guide? @nmcdavid @noahbartlett Also can you post the link to the dashboard

**Comment by nmcdavid** [comment]
@jaliasd I've updated the task list to include links to the QA/QC doc and the Tableau Dashboards on the USAID Server

**Comment by nmcdavid** [comment]
@mariaau2222

**Comment by mariaau2222** [comment]
Hi Aaron, could you kindly add me to this link so I can edit please?  mariaau2222

**Comment by noahbartlett** [comment]
[Link to Q3 dashboard](https://tableau.usaid.gov/views/Q3QuarterlyOHADashboard/Intro?iframeSizedToWindow=true&:embed=y&:showAppBanner=false&:display_count=no&:showVizHome=no)

**Comment by achafetz** [comment]
@mariaau2222 your invite is still pending from last quarter. I edited it but don't know if it resent

![image](https://user-images.githubusercontent.com/8933069/44736026-1bb1a280-aabc-11e8-8d17-7c7727380938.png)

**Comment by mariaau2222** [comment]
negative on the invite....

**Comment by achafetz** [comment]
Deleted the original invite and just reinvited you. Let me know if that works.

**Comment by mariaau2222** [comment]
It did!  Thank you!
