### ISSUE TITLE
TASK LIST Q4

### ISSUE THREAD

**Issue by jrose202** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#47]
[Link](https://docs.google.com/document/d/1AyCoNM3aVjnES0ZwkvfU5bT3zextFjdJt1fbFtc_5sU/edit?usp=sharing) to QA/QC Guide

Link to Dashboards on USAID Server

Check off once you have completed review for data through Q3
(Q4 checklist to follow)

- [x]  Global 01: Target Achievement - Christy
- [ ] OU.01: Percent Achievement - Aaron 
- [ ] OU.02: Agency Contribution - Aaron  
- [ ]  OU.03: Quarterly Trends - Aaron
- [x]  OU.04: Partner Achievement - Christy
- [ ]  OU.05: Partner Comparison - Christy
- [ ]  OU.06: Partner Contribution - Christy
- [ ]  OU.07: Age/Sex Results - Aaron
- [x]  TX.01: Retention - Nashiva
- [ ]  TX.02: Retention Age/Sex - Nashiva
- [x]  TX.03: Viral Load - Nashiva
- [ ]  TX.04: Viral Load Age/Sex - Nashiva
- [x]  TX.05: TX_CURR with VL - Nashiva
- [x]  TX.06: Linkage - Nashiva
- [x]  HTS.01: Modality - Jessica
- [x]  HTS.02: Positivity by Age/Sex - Jessica
- [x]  HTS.03: Index Testing - Jessica
- [ ]  PMTCT.01: Positivity - Nashiva
- [x]  KP.01: KP_PREV - Maria
- [x]  KP.02: HTS - Maria 
- [x]  KP.03: PrEP - Maria
- [x]  KP.04: TX_NEW - Maria
- [ ]  VMMC.01: Age Bands - Josh
- [ ]  VMMC.02: Age Trends - Josh
- [ ]  Local Partners - Melaku

**Comment by jrose202** [comment]
sorry - accidentally closed it  - should be reopened!

**Comment by nmcdavid** [comment]
@noahbartlett - hey there. For the PMTCT.01: Positivity  tab can we specify that this is among newly identified PMTCT_STAT? (it looks like it is but correct me if I'm wrong)
