### ISSUE TITLE
Task list Q4 -Q3 and Q4 checklists

### ISSUE THREAD

**Issue by jrose202** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#48]
Link to Dashboards on USAID Server

Check off once you have completed review for data through **Q3**
(Q4 checklist to follow)

- [x]  Global 01: Target Achievement - Christy
- [ ] OU.01: Percent Achievement - Aaron 
- [ ] OU.02: Agency Contribution - Aaron  
- [ ]  OU.03: Quarterly Trends - Aaron
- [x]  OU.04: Partner Achievement - Christy
- [x]  OU.05: Partner Comparison - Christy
- [x]  OU.06: Partner Contribution - Christy
- [ ]  OU.07: Age/Sex Results - Aaron
- [x]  TX.01: Retention - Nashiva
- [x]  TX.02: Retention Age/Sex - Nashiva
- [x]  TX.03: Viral Load - Nashiva
- [x]  TX.04: Viral Load Age/Sex - Nashiva
- [x]  TX.05: TX_CURR with VL - Nashiva
- [x]  TX.06: Linkage - Nashiva
- [x]  HTS.01: Modality - Jessica
- [x]  HTS.02: Positivity by Age/Sex - Jessica
- [x]  HTS.03: Index Testing - Jessica
- [ ]  PMTCT.01: Positivity - Nashiva
- [x]  KP.01: KP_PREV - Maria
- [x]  KP.02: HTS - Maria 
- [x]  KP.03: PrEP - Maria
- [x]  KP.04: TX_NEW - Maria
- [ ]  VMMC.01: Age Bands - Josh
- [ ]  VMMC.02: Age Trends - Josh
- [x]  Local Partners - Melaku

**Q4:**, #49 
- [x]  Global 01: Target Achievement - Gina
- [x] OU.01: Percent Achievement - Gina 
- [x] OU.02: Agency Contribution - Gina  
- [x]  OU.03: Quarterly Trends - Gina
- [x]  OU.04: Partner Achievement - Gina
- [x]  OU.05: Partner Comparison - Gina
- [x]  OU.06: Partner Contribution - Gina
- [x]  OU.07: Age/Sex Results - Gina
- [x]  TX.00: Cascade - Jessica
- [ ] TX.01: Retention - Jessica (issue noted - SGAC)
- [ ]  TX.02: Retention Age/Sex - Jessica (issue noted - SGAC)
- [x]  TX.03: Viral Load - Jessica (minor issues)
- [x]  TX.04: Viral Load Age/Sex - Jessica (minor issues)
- [x]  TX.05: TX_CURR with VL - Jessica (need to add in Null)
- [x]  TX.06: Linkage - Jessica
- [x]  HTS.01: Modality - Jessica
- [x] HTS.02: Age breakdown - Jessica
- [x] HTS.03: Positivity by Age/Sex - Jessica
- [x]  HTS.04: Index Testing - Jessica
- [ ]  PMTCT.01: Positivity - Melaku
- [x]  KP.01: KP_PREV - Melaku
- [x]  KP.02: HTS - Melaku
- [x]  KP.03: PrEP - Melaku
- [x]  KP.04: TX_NEW - Melaku
- [x]  VMMC.01: Age Bands - Melaku
- [x]  VMMC.02: Age Trends - Melaku
- [x]  Local Partners - Melaku

**Comment by mmdessie1** [comment]
I have checked Local partners dashboard. No error found. I compared the data from dashboard against the data from panorama for South Africa, Haiti, Vietnam and South Sudan. The Tableau dashboard pulled targets and results correctly .
Thanks,
Melaku
