### ISSUE TITLE
FY19 Q1 (Unclean) Tableau Dashboard QA/QC First Pass - COB Monday 2.25.2019

### ISSUE THREAD

**Issue by nmcdavid** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#50]
- [x] Global 01: Target Achievement @achafetz (#65) -> no data issues, but needs review
- [x] OU.01: Percent Achievement @achafetz (#61)
- [x] OU.02: Agency Contribution @achafetz (#62)
- [x] OU.03: Quarterly Trends @achafetz (#63)
- [x] OU.04: Partner Achievement @gsarfaty 
- [x] OU.06: Partner Contribution @gsarfaty 
- [x] OU.07: Age/Sex Results @gsarfaty 
- [ ] TX.01: Cascade @jaliasd 
- [ ] TX.02: Peds Cascade @jaliasd
- [ ] TX.03: Linkage @noahbartlett 
- [x] TX.04: Linkage Age/Sex @gsarfaty 
- [ ] TX.05: Retention Proxy @jaliasd
- [ ] TX.06: Retention Proxy Age/Sex @jaliasd
- [ ] TX.07: VL Coverage @jaliasd
- [x] TX.08: VL Coverage Age/Sex @mmdessie1 
- [x] TX.09: VL @mmdessie1 
- [x] TX.10: VL Age/Sex @mmdessie1 
- [x] HTS.01: Trend in Modality @cwahle 
- [x] HTS.02: Finding Men @cwahle
- [x] HTS.03: Index Testing @cwahle
- [x] HTS.04: Positivity by Age/Sex @cwahle
- [ ] HTS.05: Age Trends @noahbartlett 
- [ ] TB.01: Screen Neg @cnichols3h 
- [ ] TB.02: Screen Pos @cnichols3h 
- [x] PMTCT.01: Positivity @nmcdavid (#55 #56)
- [x] PMTCT.02: Newly Identified @nmcdavid (#57)
- [x] PMTCT.03: Newly Identified Yield @nmcdavid (#58)
- [x] KP.00: Cascade @gsarfaty
- [x] KP.01: KP_PREV  @gsarfaty
- [x] KP.02: HTS @nmcdavid
- [x] KP.03: TX_NEW @nmcdavid
- [ ] KP.04: PrEP @noahbartlett 
- [ ] VMMC.01: Age Bands  @cnichols3h 
- [ ] VMMC.02: Age Trends  @cnichols3h 
- [x] Local Partners @mmdessie1

**Comment by cnichols3h** [comment]
@nmcdavid @jrose202 thanks!  when is this due?

**Comment by nmcdavid** [comment]
@cnichols3h - hoping the first pass can be done by COB today!

**Comment by nmcdavid** [comment]
https://github.com/USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC/issues/56

**Comment by nmcdavid** [comment]
FIRST PASS - PMTCT.01 Positivity - FY18 results pullling from wrong standard disaggregate #56

**Comment by nmcdavid** [comment]
FIRST PASS - PMTCT.01 Positivity - Missing Age Disaggregation #55

**Comment by nmcdavid** [comment]
FIRST PASS - PMTCT.02 Newly Identified - Missing Age Disaggregation #58

**Comment by nmcdavid** [comment]
FIRST PASS - PMTCT.03 Newly Identified Yield- Missing Age Disaggregation #58

**Comment by achafetz** [comment]
ALL, just be aware that Malawi's reporting is limited to 5.5 of their 29 districts for most disaggregation (eg HTS_TST_POS, Age/Sex, etc).

**Comment by jrose202** [comment]
that would explain why even Panorama's numbers for Malawi don't add up.  I think.

**Comment by achafetz** [comment]
They can only get manually entered data from 5.5 districts and the rest is the community partners entering manually. DATIM and all downstream sources will not reflect what is going on in Malawi. 

In theory, they will be entering more of their Q1 (and future quarterly) data into Analytic Workspaces for HQ review. I have not (yet) been given access so I can't see if this actually happened.

**Comment by mmdessie1** [comment]
FIRSTPASS: TX08: tooltip includes proxy retention rather than proxy VL coverage . I think the formula is not correct ?

**Comment by jrose202** [comment]
Reminder to everyone - if you have completed something on the list assigned to you please check the box so we know it has been done

**Comment by nmcdavid** [comment]
No First Pass  #done

* [ ]  TX.01: Cascade @jaliasd
* [ ]  TX.02: Peds Cascade @jaliasd
* [ ]  TX.03: Linkage @noahbartlett
* [ ]  TX.05: Retention Proxy @jaliasd
* [ ]  TX.06: Retention Proxy Age/Sex @jaliasd
* [ ]  TX.07: VL Coverage @jaliasd
* [ ]  HTS.05: Age Trends @noahbartlett
* [ ]  TB.01: Screen Neg @cnichols3h
* [ ]  TB.02: Screen Pos @cnichols3h
* [ ]  KP.04: PrEP @noahbartlett
* [ ]  VMMC.01: Age Bands  @cnichols3h
* [ ]  VMMC.02: Age Trends  @cnichols3h
